# Global Oil Prices & Geopolitical Events(2010-2026)

This Jupyter notebook was created to analyze the current state of the Oil Market in terms of metrics such as Brent and WTI Crude Oil Prices. The data was gathered from: https://www.kaggle.com/datasets/kavyadhyani/global-oil-prices-and-geopolitical-events/data

In [8]:
# Load libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

First, we load the two .csv files into `DataFrame` objects.

In [9]:
events_df = pd.read_csv('data/geopolitical_events_timeline.csv')
oil_df = pd.read_csv('data/oil_geopolitics_dataset_2010_2026.csv')

In [10]:
# Check first few rows of the oil-related events
events_df.head()

         date  event_type                  event_description  event_severity
0  2010-04-20    disaster        Deepwater Horizon oil spill               7
1  2011-02-15         war            Libyan Civil War begins               9
2  2011-03-19         war         NATO intervention in Libya               9
3  2012-01-23   sanctions  EU embargo on Iranian oil imports               8
4  2014-03-18  annexation              Russia annexes Crimea               8

In [18]:
events_df.shape

(35, 4)

The data above contains events that played a role in influencing the price of oil at specific points in time. It shows a description and the nature of the event, the data it occurred, as well as how much it affected oil prices.

In [14]:
# Check first few rows of the oil prices
oil_df.head()

,date,brent_price,wti_price,dxy_index,vix,gpr_index,brent_return,wti_return,brent_lag_1,brent_lag_3,...,wti_lag_7,brent_volatility_7d,brent_volatility_30d,wti_volatility_7d,wti_volatility_30d,brent_wti_spread,event_type,event_description,event_severity,event_flag
0,2010-02-17,76.269997,77.330002,80.379997,21.719999,80.725357,0.007796,0.004155,75.680000,73.050003,...,71.190002,0.014461,0.019679,0.016977,0.019280,-1.060005,none,none,0.0,0
1,2010-02-18,77.779999,79.059998,80.400002,20.629999,80.725357,0.019798,0.022372,76.269997,72.900002,...,71.889999,0.014387,0.020019,0.017366,0.019756,-1.279999,none,none,0.0,0
2,2010-02-19,78.190002,79.809998,80.639999,20.020000,80.725357,0.005271,0.009486,77.779999,75.680000,...,73.750000,0.013342,0.019796,0.016553,0.019559,-1.619995,none,none,0.0,0
3,2010-02-22,78.610001,80.160004,80.510002,19.940001,80.725357,0.005372,0.004385,78.190002,76.269997,...,74.519997,0.013366,0.019823,0.016772,0.019561,-1.550003,none,none,0.0,0
4,2010-02-23,77.250000,78.860001,80.849998,21.370001,80.725357,-0.017301,-0.016218,78.610001,77.779999,...,75.279999,0.017334,0.020045,0.019608,0.019756,-1.610001,none,none,0.0,0